language: ruby
rvm:
  - ruby-1.9.3-p484

before_script:
  - RAILS_ENV=test

notifications:
  email: false

cache:
  - bundler

before_script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rake db:create
  - cd spec/dummy; RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..

addons:
  code_climate:
    repo_token: f54267de73817e8dcc14ccfaff327056723eaae101507c70b391bec5d5825c73

script: "bundle exec rspec --format progress"
